version = 0.1

[default.global.parameters]
stack_name = "tenanttracker-lambda"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name        = "tenanttracker-lambda"
s3_bucket         = "tenanttracker-sam-artifacts-667802015944"
s3_prefix         = "tenanttracker"
region            = "us-east-1"
confirm_changeset = false
capabilities      = "CAPABILITY_IAM"
no_fail_on_empty_changeset = true
